src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'date')]
    private $date_sortie;

    #[ORM\Column(type: 'string', length: 255)]
    private $producteur;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getProducteur(): ?string
    {
        return $this->producteur;
    }

    public function setProducteur(string $producteur): self
    {
        $this->producteur = $producteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Entity/Serie.php
<?php

namespace App\Entity;

use App\Repository\SerieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SerieRepository::class)]
class Serie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $producteur;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $nombre_episodes;

    #[ORM\Column(type: 'date')]
    private $date_sortie;

    #[ORM\ManyToMany(targetEntity: Univers::class, inversedBy: 'series')]
    private $Univers;

    public function __construct()
    {
        $this->Univers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getProducteur(): ?string
    {
        return $this->producteur;
    }

    public function setProducteur(string $producteur): self
    {
        $this->producteur = $producteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNombreEpisodes(): ?int
    {
        return $this->nombre_episodes;
    }

    public function setNombreEpisodes(int $nombre_episodes): self
    {
        $this->nombre_episodes = $nombre_episodes;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    /**
     * @return Collection<int, Univers>
     */
    public function getUnivers(): Collection
    {
        return $this->Univers;
    }

    public function addUniver(Univers $univer): self
    {
        if (!$this->Univers->contains($univer)) {
            $this->Univers[] = $univer;
        }

        return $this;
    }

    public function removeUniver(Univers $univer): self
    {
        $this->Univers->removeElement($univer);

        return $this;
    }

    
    public function __toString()
    {
        return $this->getTitre();
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('date_sortie',  DateType::class, [
                'label' => 'Date de sortie',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => [
                    'class' => 'js-datepicker',
                    'data-provide' => 'datepicker',
                    'data-date-format' => 'yyyy-mm-dd',
                    'data-date-language' => 'fr',
                    'data-date-autoclose' => 'true',
                ],
            ])
            ->add('producteur')
            ->add('description')
            // Ajouter un champ mappé au film
            ->add('Univers')
            // Ajouter des champs "non mappés" au formulaire
            ->add('conditions', CheckboxType::class, [
                'label' => 'J\'accepte les conditions d\'utilisation',
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/film')]
class FilmController extends AbstractController
{
    #[Route('/', name: 'app_film_index', methods: ['GET'])]
    public function index(FilmRepository $filmRepository): Response
    {
        return $this->render('film/index.html.twig', [
            'films' => $filmRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_film_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FilmRepository $filmRepository): Response
    {
        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filmRepository->add($film, true);

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/new.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_show', methods: ['GET'])]
    public function show(Film $film): Response
    {
        return $this->render('film/show.html.twig', [
            'film' => $film,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_film_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Film $film, FilmRepository $filmRepository): Response
    {
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $filmRepository->add($film, true);

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/edit.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_delete', methods: ['POST'])]
    public function delete(Request $request, Film $film, FilmRepository $filmRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$film->getId(), $request->request->get('_token'))) {
            $filmRepository->remove($film, true);
        }

        return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('app_film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">Delete</button>
</form>

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_film_index') }}">back to list</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film index
{% endblock %}

{% block body %}
	<h1>Film index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Titre</th>
				<th>Date_sortie</th>
				<th>Producteur</th>
				<th>Description</th>
				<th>Univers</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for film in films %}
				<tr>
					<td>{{ film.id }}</td>
					<td>{{ film.titre }}</td>
					<td>{{ film.dateSortie ? film.dateSortie|date('d M Y') : '' }}</td>
					<td>{{ film.producteur }}</td>
					<td>{{ film.description }}</td>
					<td>
						{% for univer in film.Univers %}
							<a href={{url('app_univers_show', { id: univer.id } )}}>{{ univer }}</a>,
						{% endfor %}
					</td>
					<td>
						<a href="{{ path('app_film_show', {'id': film.id}) }}">show</a>
						<a href="{{ path('app_film_edit', {'id': film.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_film_new') }}">Create new</a>
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film{% endblock %}

{% block body %}
    <h1>Create new Film</h1>

    {{ include('film/_form.html.twig') }}

    <a href="{{ path('app_film_index') }}">back to list</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film
{% endblock %}

{% block body %}
	<h1>Film</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ film.id }}</td>
			</tr>
			<tr>
				<th>Titre</th>
				<td>{{ film.titre }}</td>
			</tr>
			<tr>
				<th>Date_sortie</th>
				<td>{{ film.dateSortie ? film.dateSortie|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Producteur</th>
				<td>{{ film.producteur }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ film.description }}</td>
			</tr>
			{% if film.univers | length > 0 %}
				<tr>
					<th>Univers</th>
					<td>
						{% for univer in film.univers %}
							<a href={{ url('app_univers_show', { id: univer.id } ) }}>{{ univer }}</a>,
						{% endfor %}
					</td>
				</tr>
			{% endif %}
		</tbody>
	</table>

	<a href="{{ path('app_film_index') }}">back to list</a>

	<a href="{{ path('app_film_edit', {'id': film.id}) }}">edit</a>

	{{ include('film/_delete_form.html.twig') }}
{% endblock %}