src/Entity/Serie.php
<?php

namespace App\Entity;

use App\Repository\SerieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SerieRepository::class)]
class Serie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $producteur;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $nombre_episodes;

    #[ORM\Column(type: 'date')]
    private $date_sortie;

    #[ORM\ManyToMany(targetEntity: Univers::class, inversedBy: 'series')]
    private $Univers;

    public function __construct()
    {
        $this->Univers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getProducteur(): ?string
    {
        return $this->producteur;
    }

    public function setProducteur(string $producteur): self
    {
        $this->producteur = $producteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNombreEpisodes(): ?int
    {
        return $this->nombre_episodes;
    }

    public function setNombreEpisodes(int $nombre_episodes): self
    {
        $this->nombre_episodes = $nombre_episodes;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    /**
     * @return Collection<int, Univers>
     */
    public function getUnivers(): Collection
    {
        return $this->Univers;
    }

    public function addUniver(Univers $univer): self
    {
        if (!$this->Univers->contains($univer)) {
            $this->Univers[] = $univer;
        }

        return $this;
    }

    public function removeUniver(Univers $univer): self
    {
        $this->Univers->removeElement($univer);

        return $this;
    }

    
    public function __toString()
    {
        return $this->getTitre();
    }
}

src/Form/SerieType.php
<?php

namespace App\Form;

use App\Entity\Serie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SerieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('producteur')
            ->add('description')
            ->add('nombre_episodes')
            ->add(
                'date_sortie',
                DateType::class,
                [
                    'widget' => 'single_text',
                    'format' => 'yyyy-MM-dd',
                    'attr' => [
                        'class' => 'js-datepicker',
                        'data-provide' => 'datepicker',
                        'data-date-format' => 'yyyy-mm-dd',
                        'data-date-language' => 'fr',
                        'data-date-autoclose' => 'true',
                    ],
                ]
            )
            ->add('Univers');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Serie::class,
        ]);
    }
}

src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Serie;
use App\Form\SerieType;
use App\Repository\SerieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/serie')]
class SerieController extends AbstractController
{
    #[Route('/', name: 'app_serie_index', methods: ['GET'])]
    public function index(SerieRepository $serieRepository): Response
    {
        return $this->render('serie/index.html.twig', [
            'series' => $serieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_serie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SerieRepository $serieRepository): Response
    {
        $serie = new Serie();
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serieRepository->add($serie, true);

            return $this->redirectToRoute('app_serie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('serie/new.html.twig', [
            'serie' => $serie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_serie_show', methods: ['GET'])]
    public function show(Serie $serie): Response
    {
        return $this->render('serie/show.html.twig', [
            'serie' => $serie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_serie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Serie $serie, SerieRepository $serieRepository): Response
    {
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serieRepository->add($serie, true);

            return $this->redirectToRoute('app_serie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('serie/edit.html.twig', [
            'serie' => $serie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_serie_delete', methods: ['POST'])]
    public function delete(Request $request, Serie $serie, SerieRepository $serieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$serie->getId(), $request->request->get('_token'))) {
            $serieRepository->remove($serie, true);
        }

        return $this->redirectToRoute('app_serie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/serie/_delete_form.html.twig
<form method="post" action="{{ path('app_serie_delete', {'id': serie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ serie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/serie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/serie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Serie{% endblock %}

{% block body %}
    <h1>Edit Serie</h1>

    {{ include('serie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_serie_index') }}">back to list</a>

    {{ include('serie/_delete_form.html.twig') }}
{% endblock %}

templates/serie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Serie index{% endblock %}

{% block body %}
    <h1>Serie index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Producteur</th>
                <th>Description</th>
                <th>Nombre_episodes</th>
                <th>Date_sortie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for serie in series %}
            <tr>
                <td>{{ serie.id }}</td>
                <td>{{ serie.titre }}</td>
                <td>{{ serie.producteur }}</td>
                <td>{{ serie.description }}</td>
                <td>{{ serie.nombreEpisodes }}</td>
                <td>{{ serie.dateSortie ? serie.dateSortie|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_serie_show', {'id': serie.id}) }}">show</a>
                    <a href="{{ path('app_serie_edit', {'id': serie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_serie_new') }}">Create new</a>
{% endblock %}

templates/serie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Serie{% endblock %}

{% block body %}
    <h1>Create new Serie</h1>

    {{ include('serie/_form.html.twig') }}

    <a href="{{ path('app_serie_index') }}">back to list</a>
{% endblock %}

templates/serie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Serie{% endblock %}

{% block body %}
    <h1>Serie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ serie.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ serie.titre }}</td>
            </tr>
            <tr>
                <th>Producteur</th>
                <td>{{ serie.producteur }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ serie.description }}</td>
            </tr>
            <tr>
                <th>Nombre_episodes</th>
                <td>{{ serie.nombreEpisodes }}</td>
            </tr>
            <tr>
                <th>Date_sortie</th>
                <td>{{ serie.dateSortie ? serie.dateSortie|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_serie_index') }}">back to list</a>

    <a href="{{ path('app_serie_edit', {'id': serie.id}) }}">edit</a>

    {{ include('serie/_delete_form.html.twig') }}
{% endblock %}